---

# This script contains commands to run cypress.io tests from docroot/cypress directory.

- name: Install dependencies
  shell: cd cypress && yarn install
  sudo: yes

- name: Make sure "build_reports" already exists
  file:
    path: build_reports
    state: directory
    mode: 0777
  sudo: yes

- name: Run tests
  shell: env CYPRESS_baseUrl="{{ site_url }}" node_modules/cypress/bin/cypress run --reporter=nyan
  args:
    chdir: cypress
  sudo: yes
  ignore_errors: true
  register: report

- name: Output test results header
  shell: echo "<!DOCTYPE html><html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><title>Build results for {{ site_url }}</title></head><body><code>" > cypress.html
  args:
    chdir: build_reports
  sudo: yes

- name: Output test results body
  shell: echo "{{ report.stdout }}" >> cypress.html
  args:
    chdir: build_reports
  sudo: yes

- name: Output test results tail
  shell: echo "</code></body></html>" >> cypress.html
  args:
    chdir: build_reports
  sudo: yes
