---
# This script contains commands to build react applications from docroot/reactapps folder.
- name: Install dependencies
  shell: cd reactapps/prgreg && yarn install
  sudo: yes
  
- name: Build application
  shell: cd reactapps/prgreg && yarn build
  sudo: yes

- name: ReactApp url
  sudo: yes
  lineinfile: dest={{ workspace_root }}/{{ artifacts_file }} line="Program Registration App installed at {{ webroot }}/reactapps/prgreg/build/" create=yes state=present
