id: ymca_migrate_url_alias_location_schedule
label: 'URL aliases for location schedules pages'
migration_group: ymca
migration_tags:
  - node
source:
  plugin: ymca_migrate_url_alias_location_schedule
process:
  source: source
  alias: alias
  langcode:
    plugin: default_value
    default_value: en
destination:
  plugin: url_alias
migration_dependencies:
  required:
    - ymca_migrate_node_location
