staging:
  sourcename: YMCAoftheGreaterTwinCities
  password: W4aW8jPH1tR1KbdSEyDK1jdiQfY=
  site_id: '-99'
  user_name: Siteowner
  user_password: apitest1234
production:
  sourcename: YMCAoftheGreaterTwinCities
  password: W4aW8jPH1tR1KbdSEyDK1jdiQfY=
  site_id: '249173'
  user_name: alexander.schedrov@ffwagency.com
  user_password: JOkrxVlp3M6em3QTIyYx
active: production
