page_title: 'Sitemap Navigation'
message:
  value: ''
  format: full_html
show_front: false
show_titles: false
show_books: {  }
books_expanded: true
show_menus:
  camps: camps
  child-care-preschool: child-care-preschool
  community-programs: community-programs
  health-and-fitness: health-and-fitness
  jobs-suppliers-news: jobs-suppliers-news
  kids-teen-activities: kids-teen-activities
  locations: locations
  swimming: swimming
  account: '0'
  admin: '0'
  devel: '0'
  footer: '0'
  footer-menu-center: '0'
  footer-menu-left: '0'
  footer-menu-right: '0'
  main: '0'
  main-menu: '0'
  our-cause: '0'
  tools: '0'
  top-menu: '0'
show_menus_hidden: false
show_vocabularies:
  activity: '0'
  tags: '0'
show_description: true
show_count: true
vocabulary_depth: -1
term_threshold: 0
forum_threshold: -1
rss_front: rss.xml
show_rss_links: 0
rss_taxonomy: -1
css: false
order:
  front: -50
  menus_account: -50
  menus_admin: -50
  menus_camps: -50
  menus_child-care-preschool: -50
  menus_community-programs: -50
  menus_devel: -50
  menus_footer: -50
  menus_footer-menu-center: -50
  menus_footer-menu-left: -50
  menus_footer-menu-right: -50
  menus_health-and-fitness: -50
  menus_jobs-suppliers-news: -50
  menus_kids-teen-activities: -50
  menus_locations: -50
  menus_main: -50
  menus_main-menu: -50
  menus_our-cause: -50
  menus_swimming: -50
  menus_tools: -50
  menus_top-menu: -50
  vocabularies_activity: -50
  vocabularies_tags: -50
_core:
  default_config_hash: qZeaiLq06xBUfw-JNZtgetxUUMz-J8YCzw_LuhPrk2E
