smtp_on: true
smtp_host: 178.62.224.139
smtp_hostbackup: ''
smtp_port: '1025'
smtp_protocol: standard
smtp_username: ''
smtp_password: ''
smtp_from: from_redwing_smtp@localhost.com
smtp_fromname: 'Testing Emails'
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: false
_core:
  default_config_hash: ZfbmfcSfeKOEssW5y01Z6rijotca6J_bKMFGQ1t0GD0
