items:
  1302:
    show: 1
    overview: 1
  2153:
    show: 1
    overview: 1
  1035:
    show: 1
    overview: 1
  1480:
    show: 1
    overview: 1
  385:
    show: 1
    overview: 1
  2715:
    show: 1
    overview: 1
