date_campaign_open: '8/3/2016 12:00 AM'
date_campaign_close: '8/16/2016 11:59 PM'
date_registration_open: '7/25/2016 12:00 AM'
date_registration_close: '8/16/2016 11:59 PM'
date_reporting_open: '8/3/2016 12:00 AM'
date_reporting_close: '8/16/2016 11:59 PM'
new_member_goal_number: '5'
limit_goal_number: '10'
date_checkins_start: '5/30/2016 12:00 AM'
date_checkins_end: '7/24/2016 11:59 PM'
date_winners_announcement: '8/31/2016 12:00 AM'
