openy_programs_search.settings:
  type: config_object
  label: 'OpenY Programs Search'
  mapping:
    client_id:
      type: text
      label: 'Daxko Client ID'
    base_url:
      type: text
      label: 'Daxko Base URL'
    registration_link:
      type: text
      label: 'Daxko Registration Link'
    scrape_daxko_schools_by_program:
      type: text
      label: 'Scrape Daxko Schools By Program'
