name: 'OpenY Theme Settings'
description: 'Provides configuration for OpenY theme.'
type: module
core: 8.x
dependencies:
  - block
  - color
  - metatag
  - page_manager
  - user
  - views
  - ymca_page_manager
version: 8.x-1.0
