ymca_migrate.settings:
  type: config_object
  label: YMCA migrate settings
  mapping:
    cache_dir:
      type: string
      label: Path to cache directory
    url_prefix:
      type: string
      label: URL prefix to the assets
    timezone:
      type: string
      label: Timezone
