name: Config Import
description: Clever configuration import.
package: Configuration
type: module
# core: 8.x

# Information added by Drupal.org packaging script on 2016-12-08
version: '8.x-1.1'
core: '8.x'
project: 'confi'
datestamp: 1481157485
