definitions:
  contact__site_page:
    weight: -46
    menu_name: footer
    parent: ''
    enabled: false
    expanded: false
  ymca_personify__sign_in:
    weight: -50
    menu_name: top-menu
    parent: ''
    enabled: true
    expanded: false
  ymca_personify__account:
    weight: -50
    menu_name: top-menu
    parent: ''
    expanded: true
    enabled: true
  ymca_personify__childcare_payment_history:
    weight: -49
    menu_name: top-menu
    parent: ymca_personify.account
    enabled: true
    expanded: false
  ymca_personify__account_my:
    weight: -50
    menu_name: top-menu
    parent: ymca_personify.account
    expanded: false
    enabled: true
  ymca_personify__sign_out:
    weight: -48
    menu_name: top-menu
    parent: ymca_personify.account
    expanded: false
    enabled: true
