header_replacements:
  -
    block_id: 'Disable Mobile Section Lead Copy'
    selector: '.page-middle .lead-copy'
  -
    block_id: 'Disable header'
    selector: .nav-global
footer_replacements:
  -
    block_id: 'Disable Footer'
    selector: '#page-footer'
header_footer_independent_replacements:
  -
    block_id: 'Disable Toolbar'
    selector: '.independent-header #toolbar-bar'
  -
    block_id: 'Disable Mobile Section  sign in'
    selector: '.independent-header .sidebar > .col-xs-12'
  -
    block_id: 'Disable Mobile Section  search'
    selector: '.independent-header .sidebar > form'
  -
    block_id: 'Disable sign in'
    selector: '.independent-header #block-top-menu-2 .nav li:nth-child(3)'
  -
    block_id: 'Disable search'
    selector: '.independent-header #block-top-menu-2 .nav li:nth-child(5)'
_core:
  default_config_hash: YQujmiHzDkcPOFQcexA9cT0yY9p2UdYh3RKZDIS672g
