custom:
  -
    path: /
    priority: !!float 1
entity_types:
  node_type:
    blog:
      index: 1
      priority: 0.5
    camp:
      index: 1
      priority: 0.5
    location:
      index: 1
      priority: 0.5
    article:
      index: 1
      priority: 0.5
      entities:
        1338:
          index: 0
          priority: 0.5
        497:
          index: 0
          priority: 0.5
        802:
          index: 0
          priority: 0.5
        1033:
          index: 0
          priority: 0.5
        1228:
          index: 0
          priority: 0.5
        1381:
          index: 0
          priority: 0.5
        1509:
          index: 0
          priority: 0.5
        1612:
          index: 0
          priority: 0.5
        1681:
          index: 0
          priority: 0.5
        504:
          index: 0
          priority: 0.5
        565:
          index: 0
          priority: 0.5
        1060:
          index: 0
          priority: 0.5
        1892:
          index: 0
          priority: 0.5
        625:
          index: 0
          priority: 0.5
        1066:
          index: 0
          priority: 0.5
        692:
          index: 0
          priority: 0.5
        574:
          index: 0
          priority: 0.5
        1082:
          index: 0
          priority: 0.5
        1084:
          index: 0
          priority: 0.5
        1086:
          index: 0
          priority: 0.5
        1088:
          index: 0
          priority: 0.5
        1092:
          index: 0
          priority: 0.5
        1094:
          index: 0
          priority: 0.5
        1095:
          index: 0
          priority: 0.5
        1100:
          index: 0
          priority: 0.5
        1101:
          index: 0
          priority: 0.5
        1105:
          index: 0
          priority: 0.5
        1108:
          index: 0
          priority: 0.5
        1109:
          index: 0
          priority: 0.5
        1110:
          index: 0
          priority: 0.5
        1112:
          index: 0
          priority: 0.5
        1114:
          index: 0
          priority: 0.5
        1117:
          index: 0
          priority: 0.5
        1119:
          index: 0
          priority: 0.5
        1121:
          index: 0
          priority: 0.5
        1124:
          index: 0
          priority: 0.5
        1125:
          index: 0
          priority: 0.5
        1128:
          index: 0
          priority: 0.5
        1132:
          index: 0
          priority: 0.5
        500:
          index: 0
          priority: 0.5
        494:
          index: 0
          priority: 0.5
        488:
          index: 0
          priority: 0.5
        489:
          index: 0
          priority: 0.5
        499:
          index: 0
          priority: 0.5
        1115:
          index: 0
          priority: 0.5
        1083:
          index: 0
          priority: 0.5
        541:
          index: 0
          priority: 0.5
        540:
          index: 0
          priority: 0.5
        581:
          index: 0
          priority: 0.5
        1075:
          index: 0
          priority: 0.5
        1878:
          index: 0
          priority: 0.5
        1370:
          index: 0
          priority: 0.5
        2166:
          index: 0
          priority: 0.5
        1876:
          index: 0
          priority: 0.5
        2169:
          index: 0
          priority: 0.5
        2183:
          index: 0
          priority: 0.5
        2216:
          index: 0
          priority: 0.5
        2506:
          index: 0
          priority: 0.5
        2656:
          index: 0
          priority: 0.5
        2733:
          index: 0
          priority: 0.5
        2741:
          index: 0
          priority: 0.5
        2642:
          index: 0
          priority: 0.5
        2693:
          index: 0
          priority: 0.5
        2670:
          index: 0
          priority: 0.5
        2643:
          index: 0
          priority: 0.5
        2711:
          index: 0
          priority: 0.5
        2695:
          index: 0
          priority: 0.5
        2671:
          index: 0
          priority: 0.5
        2696:
          index: 0
          priority: 0.5
        2735:
          index: 0
          priority: 0.5
        2673:
          index: 0
          priority: 0.5
        2647:
          index: 0
          priority: 0.5
        2648:
          index: 0
          priority: 0.5
        2674:
          index: 0
          priority: 0.5
        2698:
          index: 0
          priority: 0.5
        2652:
          index: 0
          priority: 0.5
        2677:
          index: 0
          priority: 0.5
        2728:
          index: 0
          priority: 0.5
        2604:
          index: 0
          priority: 0.5
        1:
          index: 0
          priority: 0.5
settings:
  max_links: 20000
  cron_generate: true
  remove_duplicates: true
  batch_process_limit: 1500
_core:
  default_config_hash: fICH612phS7-D_8q-m1YjgYFM8Mcy_5JestT1H_nkPQ
