percentage: '3'
prize_pool:
  -
    value: 5
    quantity: '2000'
  -
    value: 20
    quantity: '500'
  -
    value: 50
    quantity: '100'
  -
    value: 100
    quantity: '10'
loss_messages_short:
  - 'Keep trying'
  - 'No luck'
  - 'It was close'
  - 'Another time'
loss_messages_long_1:
  - 'You didn''t win this time.'
  - 'No prize this time.'
  - 'That chance isn''t a winner.'
  - 'You didn''t win.'
  - 'No luck this time.'
  - 'That chance didn’t win you a prize.'
loss_messages_long_2:
  - 'Stay active for more chances to win.'
  - 'Complete more challenge activities to try again.'
  - 'Show your Y spirit for another shot at prizes.'
  - 'Keep up the great work to give it another shot.'
  - 'Keep coming back to check the chances you earn.'
  - 'But you''re really showing your Y spirit!'
product_pool:
  - AMZN
  - AMCT
  - BRNS1
  - BSTB1
  - CVSP
  - DICK
  - GOOG
  - APPL
  - TRGT
  - WFOODS
product_pool_keyed:
  5:
    - AMZN-E-V-STD
    - BRNS1-E-V-STD
    - BSTB1-E-V-STD
    - CVSP-E-V-STD
    - APPL-E-500-STD
    - TRGT-E-V-STD
  20:
    - AMZN-E-V-STD
    - BRNS1-E-V-STD
    - BSTB1-E-V-STD
    - CVSP-E-V-STD
    - APPL-E-2000-STD
    - TRGT-E-V-STD
  50:
    - AMZN-E-V-STD
    - AMCT-E-5000-STD
    - BRNS1-E-V-STD
    - BSTB1-E-V-STD
    - CVSP-E-V-STD
    - DICK-E-5000-STD
    - GOOG-E-5000-STD
    - APPL-E-5000-STD
    - TRGT-E-V-STD
    - WFOODS-E-5000-STD
  100:
    - AMZN-E-V-STD
    - BRNS1-E-V-STD
    - BSTB1-E-V-STD
    - CVSP-E-V-STD
    - DICK-E-10000-STD
    - GOOG-E-10000-STD
    - APPL-E-10000-STD
    - TRGT-E-V-STD
    - WFOODS-E-10000-STD
