items:
  5101:
    show: '1'
    overview: 0
  5156:
    show: '1'
    overview: '1'
  5161:
    show: '1'
    overview: '1'
  5136:
    show: '1'
    overview: 0
  5221:
    show: 0
    overview: 0
  2148:
    show: 0
    overview: 0
  2149:
    show: 0
    overview: 0
  2150:
    show: 0
    overview: 0
  2411:
    show: 0
    overview: 0
  2151:
    show: 0
    overview: 0
  2152:
    show: 0
    overview: 0
  1522:
    show: 0
    overview: 0
  1302:
    show: 0
    overview: 0
  2153:
    show: 0
    overview: 0
  1035:
    show: 0
    overview: 0
  1480:
    show: 0
    overview: 0
  385:
    show: 0
    overview: 0
  2715:
    show: 0
    overview: 0
  1460:
    show: 0
    overview: 0
  1461:
    show: 0
    overview: 0
  1462:
    show: 0
    overview: 0
