date_campaign_open: '02/10/2017 12:00 AM'
date_campaign_close: '03/10/2017 11:59 PM'
date_registration_open: '02/10/2017 12:00 AM'
date_registration_close: '03/10/2017 11:59 PM'
date_reporting_open: '02/10/2017 12:00 AM'
date_reporting_close: '03/10/2017 11:59 PM'
new_member_goal_number: '5'
limit_goal_number: '10'
date_checkins_start: '01/01/2017 12:00 AM'
date_checkins_end: '02/10/2017 11:59 PM'
date_winners_announcement: '01/01/2017 12:00 AM'
calculate_visit_goal: 1
recent_winners_limit: '30'
