wsdl: 'https://ygtcprod2.personifycloud.com/sso/webservice/service.asmx?WSDL'
vendor_id: 8
vendor_username: ClockWork
vendor_password: ***REMOVED***
vendor_block: ***REMOVED***
url_login: 'http://ygtcprod2.personifycloud.com/PersonifyEBusiness/Default.aspx?TabID=337'
url_account: 'http://ygtcprod2.personifycloud.com/personifyebusiness/MyY/tabid/61/Default.aspx'
url_sign_out: 'https://ygtcprod2.personifycloud.com/personifyebusiness/MyY/tabid/61/ctl/Logoff/Default.aspx'
url_cart: 'http://ygtcprod2.personifycloud.com/PersonifyEbusiness/YMCA/ShoppingCart.aspx'
customer_orders_endpoint: 'http://ygtctrain2.personifycloud.com/personifydataservices/PersonifyData.svc/CL_MindBodyCustomerOrder'
customer_orders_username: Alex.Schedrov
customer_orders_password: A!ex!23
childcare_authorization: 'Basic QWxleC5TY2hlZHJvdjpIZWxwZGVzazAx'
childcare_endpoint: http://ygtcprod2.personifycloud.com/PersonifyDataServices/PersonifyData.svc/CL_GetChildcarePayments
