date_campaign_open: '10/15/2016 12:00 AM'
date_campaign_close: '12/14/2016 11:59 PM'
date_registration_open: '10/5/2016 12:00 AM'
date_registration_close: '12/14/2016 11:59 PM'
date_reporting_open: '10/15/2016 12:00 AM'
date_reporting_close: '12/14/2016 11:59 PM'
new_member_goal_number: '5'
limit_goal_number: '10'
date_checkins_start: '5/30/2016 12:00 AM'
date_checkins_end: '7/24/2016 11:59 PM'
date_winners_announcement: '12/30/2016 12:00 AM'
calculate_visit_goal: 0
