date_campaign_open: '03/08/2017 12:00 AM'
date_campaign_close: '09/21/2017 11:59 PM'
date_registration_open: '03/01/2017 12:00 AM'
date_registration_close: '09/21/2017 11:59 PM'
date_reporting_open: '03/08/2017 12:00 AM'
date_reporting_close: '09/21/2017 11:59 PM'
new_member_goal_number: '5'
limit_goal_number: '10'
date_checkins_start: '01/01/2017 12:00 AM'
date_checkins_end: '09/25/2017 11:59 PM'
date_winners_announcement: '09/22/2017 12:00 AM'
calculate_visit_goal: 1
recent_winners_limit: '30'
