locations:
  1:
    -
      name: 'Jake Humnick'
      email: jake.humnick@ymcamn.org
  2:
    -
      name: 'Dru Dalton'
      email: andrew.dalton@ymcamn.org
  3:
    -
      name: 'Rachel Bents'
      email: rachel.bents@ymcamn.org
  4:
    -
      name: 'Adam Becker'
      email: adam.becker@ymcamn.org
  5:
    -
      name: 'Joe Augenstein'
      email: joe.augenstein@ymcamn.org
  6:
    -
      name: 'LeAnn Niebur'
      email: leann.niebur@ymcamn.org
  7:
    -
      name: 'Beth Kanthak'
      email: beth.kanthak@ymcamn.org
  8:
    -
      name: 'Ronnie Cordova'
      email: ronnie.cordova@ymcamn.org
  9:
    -
      name: 'Anna Golv'
      email: anna.golv@ymcamn.org
  10:
    -
      name: 'Greg Kimbrough'
      email: greg.kimbrough@ymcamn.org
  11:
    -
      name: 'Donavan Haugstad'
      email: donavan.haugstad@ymcamn.org
  12:
    -
      name: 'Tim May'
      email: tim.may@ymcamn.org
  13:
    -
      name: 'Mark Smith'
      email: mark.smith@ymcamn.org
  14:
    -
      name: 'Rachel Humnick'
      email: rachel.humnick@ymcamn.org
  15:
    -
      name: 'Tim Moore'
      email: tim.moore@ymcamn.org
  16:
    -
      name: 'Becky VanDyke'
      email: rebecca.vandyke@ymcamn.org
  17:
    -
      name: 'Diana Bishop'
      email: diana.bishop@ymcamn.org
  18:
    -
      name: 'Gary Sandin'
      email: gary.sandin@ymcamn.org
  19:
    -
      name: 'Jesse Zachay'
      email: jesse.zachay@ymcamn.org
  20:
    -
      name: 'Damien Washington'
      email: damien.rochon-washington@ymcamn.org
  22:
    -
      name: 'Heidi Freitag'
      email: heidi.freitag@ymcamn.org
  23:
    -
      name: 'Velma Harris'
      email: velma.harris@ymcamn.org
  25:
    -
      name: 'Heather George'
      email: heather.george@ymcamn.org
