date_registration_open: '7/25/2016 12:00 AM'
date_registration_close: '8/16/2016 11:59 PM'
date_reporting_open: '8/3/2016 12:00 AM'
date_reporting_close: '8/16/2016 11:59 PM'
date_campaign_close: '8/22/2016 11:59 PM'
limit_goal_number: 13
date_checkins_start: '4/25/2016 12:00 AM'
date_checkins_end: '7/24/2016 11:59 PM'
