sourcename: YMCAoftheGreaterTwinCities
password: W4aW8jPH1tR1KbdSEyDK1jdiQfY=
site_id: '-99'
user_name: Siteowner
user_password: apitest1234
_core:
  default_config_hash: 5kjyyfil3-64o7Bvzv_Mk_tDXW5ppMI0E9rZGQFaOIU
