intro_header: ''
intro_body:
  value: ''
  format: full_html
intro_reg_btn: 'Sign Up Now'
info_block_1_header: 'Join The Challenge'
info_block_1_copy:
  value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus risus turpis, vestibulum mattis nisl ac, scelerisque.</p>\r\n"
  format: full_html
info_block_1_link_type: '1'
info_block_1_img:
  - '36897'
info_block_1_link: /locations
info_block_1_tab: ''
info_block_2_header: 'Achieve Your Goal'
info_block_2_copy:
  value: "<p>Nulla pulvinar justo quis sapien varius, sit amet hendrerit enim. Proin sed libero ex.</p>\r\n"
  format: full_html
info_block_2_link_type: '2'
info_block_2_img:
  - '36898'
info_block_2_link: ''
info_block_2_tab: '3'
info_block_3_header: 'Track & Win'
info_block_3_copy:
  value: "<p>Praesent vitae interdum nisi, eu accumsan tellus. Phasellus dapibus sem eget justo hendrerit malesuada.</p>\r\n"
  format: full_html
info_block_3_link_type: '2'
info_block_3_img:
  - '36899'
info_block_3_link: ''
info_block_3_tab: '2'
