bonus_codes:
  - {code: 'code01', reference: 5486}
  - {code: 'code02', reference: 5486}
  - {code: 'code03', reference: 5486}
  - {code: 'code04', reference: 5486}
  - {code: 'code05', reference: 5486}
  - {code: 'code06', reference: 5486}
  - {code: 'code07', reference: 5486}
  - {code: 'code08', reference: 5486}
  - {code: 'code09', reference: 5486}
  - {code: 'code10', reference: 5486}
  - {code: 'code11', reference: 5486}
  - {code: 'code12', reference: 5486}
  - {code: 'code13', reference: 5486}
  - {code: 'code14', reference: 5486}
  - {code: 'code15', reference: 5486}
  - {code: 'code16', reference: 5486}
  - {code: 'code17', reference: 5486}
  - {code: 'code18', reference: 5486}
  - {code: 'code19', reference: 5486}
  - {code: 'code20', reference: 5486}
  - {code: 'code21', reference: 5486}
  - {code: 'code22', reference: 5486}
  - {code: 'code23', reference: 5486}
  - {code: 'code24', reference: 5486}
  - {code: 'code25', reference: 5486}
  - {code: 'code26', reference: 5486}
  - {code: 'code27', reference: 5486}
  - {code: 'code28', reference: 5486}
  - {code: 'code29', reference: 5486}
