prize_sku: 'TNGO-E-V-STD'
prize_pool:
  -
    value: 5
    quantity: 2000
  -
    value: 20
    quantity: 500
  -
    value: 50
    quantity: 100
  -
    value: 100
    quantity: 10

percentage: 20

messages_loss:
  - 'No luck'
  - 'Keep trying'
  - 'It was close'
  - 'Another time'
