date_campaign_open: '07/01/2017 12:00 AM'
date_campaign_close: '08/01/2017 11:59 PM'
date_registration_open: '07/01/2017 12:00 AM'
date_registration_close: '08/01/2017 11:59 PM'
date_reporting_open: '07/01/2017 12:00 AM'
date_reporting_close: '08/01/2017 11:59 PM'
new_member_goal_number: '5'
limit_goal_number: '10'
date_checkins_start: '07/01/2017 12:00 AM'
date_checkins_end: '08/01/2017 11:59 PM'
date_winners_announcement: '09/22/2017 12:00 AM'
calculate_visit_goal: 1
recent_winners_limit: '30'
exclude_reg_product_codes:
  14_GETSUMMER: 14_GETSUMMER
  17_GETSUMMER: 17_GETSUMMER
  20_GETSUMMER: 20_GETSUMMER
  22_GETSUMMER: 22_GETSUMMER
  24_GETSUMMER: 24_GETSUMMER
  27_GETSUMMER: 27_GETSUMMER
  30_GETSUMMER: 30_GETSUMMER
  32_GETSUMMER: 32_GETSUMMER
  34_GETSUMMER: 34_GETSUMMER
  36_GETSUMMER: 36_GETSUMMER
  38_GETSUMMER: 38_GETSUMMER
  70_GETSUMMER: 70_GETSUMMER
  75_GETSUMMER: 75_GETSUMMER
  76_GETSUMMER: 76_GETSUMMER
  77_GETSUMMER: 77_GETSUMMER
  81_GETSUMMER: 81_GETSUMMER
  82_GETSUMMER: 82_GETSUMMER
  83_GETSUMMER: 83_GETSUMMER
  84_GETSUMMER: 84_GETSUMMER
  85_GETSUMMER: 85_GETSUMMER
  87_GETSUMMER: 87_GETSUMMER
  88_GETSUMMER: 88_GETSUMMER
  89_GETSUMMER: 89_GETSUMMER
error_msg_excluded_members:
  value: "<p><strong>Thanks for your interest in the Y Strive Challenge</strong><br />\r\nBased on your age or membership type, you're not eligible to participate. Review the rules for more info. You can still use your membership to work out at the Y and challenge yourself.</p>\r\n"
  format: full_html
error_msg_registered_before_start:
  value: "<p><strong>You’re already signed up!</strong><br />\r\nIf you didn’t already sign up, please&nbsp;<a href=\"/contact_us\" rel=\"noreferrer\" target=\"_blank\">contact us</a>. Then, come back on August 1 to start tracking your progress and reporting activities.&nbsp;</p>\r\n"
  format: full_html
error_msg_registered_after_start:
  value: "<p><strong>You’re already signed up!</strong><br />\r\nThanks for logging in. You can check your progress or report activities.</p>\r\n"
  format: full_html
error_msg_incorrect_id:
  value: "<p><strong>Please check your member ID</strong><br />\r\nIf you have entered your member ID correctly and it still isn’t working, <a href=\"/contact_us\" rel=\"noreferrer\" target=\"_blank\">contact us</a>.</p>\r\n"
  format: full_html
