bonus_codes:
  -
    code: code01
    reference: '5486'
  -
    code: code02
    reference: '5486'
  -
    code: code03
    reference: '5486'
  -
    code: code04
    reference: '5486'
  -
    code: code05
    reference: '5486'
  -
    code: code06
    reference: '5486'
  -
    code: code07
    reference: '5486'
  -
    code: code08
    reference: '5486'
  -
    code: code09
    reference: '5486'
  -
    code: code10
    reference: '5486'
  -
    code: code11
    reference: '5486'
  -
    code: code12
    reference: '5486'
  -
    code: code13
    reference: '5486'
  -
    code: code14
    reference: '5486'
