locations:
  -
    geid: 26
    name: Andover
    entity_id: 4
    machine_name: andover
  -
    geid: 33
    name: Blaisdell
    entity_id: 5
    machine_name: blaisdell
  -
    geid: 30
    name: Burnsville
    entity_id: 6
    machine_name: burnsville
  -
    geid: 16
    name: Eagan
    entity_id: 7
    machine_name: eagan
  -
    geid: 27
    name: 'Elk River'
    entity_id: 8
    machine_name: elk_river
  -
    geid: 34
    name: 'Emma B. Howe'
    entity_id: 9
    machine_name: emma_b._howe_-_coon_rapids
  -
    geid: 0
    name: 'Forest Lake'
    entity_id: 2746
    machine_name: forest_lake
  -
    geid: 19
    name: Hastings
    entity_id: 10
    machine_name: hastings
  -
    geid: 313
    name: 'Heritage Park'
    entity_id: 11
    machine_name: heritage_park
  -
    geid: 17
    name: Hudson
    entity_id: 12
    machine_name: hudson
  -
    geid: 18
    name: 'Lino Lakes'
    entity_id: 13
    machine_name: lino_lakes
  -
    geid: 28
    name: 'Minneapolis Downtown'
    entity_id: 14
    machine_name: minneapolis_downtown
  -
    geid: 1677
    name: 'Mounds View Community Center'
    entity_id: 15
  -
    geid: 31
    name: 'New Hope'
    entity_id: 16
    machine_name: new_hope
  -
    geid: 32
    name: Ridgedale
    entity_id: 17
    machine_name: ridgedale
  -
    geid: 53
    name: 'River Valley'
    entity_id: 18
    machine_name: prior_lake
  -
    geid: 14
    name: 'St. Paul Downtown'
    entity_id: 19
    machine_name: st._paul_downtown
  -
    geid: 35
    name: 'St. Paul Eastside'
    entity_id: 20
    machine_name: st._paul_eastside
  -
    geid: 12
    name: 'St. Paul Midway'
    entity_id: 21
    machine_name: st._paul_midway
  -
    geid: 20
    name: Shoreview
    entity_id: 22
    machine_name: shoreview
  -
    geid: 29
    name: Southdale
    entity_id: 23
    machine_name: southdale
  -
    geid: 25
    name: 'West St. Paul'
    entity_id: 24
    machine_name: west_st._paul
  -
    geid: 21
    name: 'White Bear Area'
    entity_id: 25
    machine_name: white_bear_area
  -
    geid: 13
    name: Woodbury
    entity_id: 26
    machine_name: woodbury
  -
    geid: 0
    name: 'North Community'
    entity_id: 27
  -
    geid: 0
    name: 'University YMCA'
    entity_id: 28
  -
    geid: 0
    name: 'Youth In Government'
    entity_id: 29
