intro_header: ''
intro_body:
  value: ''
  format: full_html
intro_reg_btn: 'Sign Up Now'
info_block_1_header: 'Overview'
info_block_1_copy:
  value: "<p>Tackle your wellness goals with gusto this summer—the Y Strive Challenge is your chance to work out, have fun, get involved and enjoy the rewards.</p>\r\n"
  format: full_html
info_block_1_link_type: '1'
info_block_1_img:
  - '36897'
info_block_1_link: /locations
info_block_1_tab: ''
info_block_2_header: 'Visit goal'
info_block_2_copy:
  value: "<p>You’re given a personal goal for how many times to visit the Y during the challenge. Meet your visit goal and earn 4 guest passes.</p>\r\n"
  format: full_html
info_block_2_link_type: '2'
info_block_2_img:
  - '36898'
info_block_2_link: ''
info_block_2_tab: '3'
info_block_3_header: 'Track activities'
info_block_3_copy:
  value: "<p>Record the Swimming, Fitness, Group Exercise and Community activities that you do. The more you track, the higher your chances of winning a prize.</p>\r\n"
  format: full_html
info_block_3_link_type: '2'
info_block_3_img:
  - '36899'
info_block_3_link: ''
info_block_3_tab: '2'
