menu_list:
  - programs-classes
  - schedules-menu
  - main-menu
  - locations
  - health-and-fitness
  - locations-var-b
  - membership-var-b
  - more-menu
  - swimming
  - child-care-preschool
  - kids-teen-activities
  - camps
  - our-cause
  - jobs-suppliers-news
