# Prod endpoint.
prod_endpoint: 'https://***REMOVED***/PersonifyDataServices/PersonifyData.svc/'
prod_username: dmitry.drozdik
prod_password: ***REMOVED***

# Stage endpoint.
stage_endpoint: 'https://ygtctrain3ebiz.personifycloud.com/PersonifyDataServices/PersonifyData.svc/'
stage_username: dmitry.drozdik
stage_password: ***REMOVED***

# Environment: stage or prod
environment: prod
