bonus_codes:
  -
    code: code01
    reference: '5406'
    video: ''
  -
    code: code02
    reference: '5186'
    video: ''
  -
    code: code03
    reference: '269'
    video: ''
  -
    code: code04
    reference: '4481'
    video: ''
  -
    code: code05
    reference: '5406'
    video: ''
  -
    code: code06
    reference: '5406'
    video: '<iframe width="716" height="400" src="https://www.youtube.com/embed/CIbFPk004Fk" frameborder="0" allowfullscreen></iframe>'
  -
    code: code07
    reference: '4361'
    video: ''
  -
    code: code08
    reference: '5406'
    video: ''
  -
    code: code09
    reference: '4351'
    video: ''
  -
    code: code10
    reference: '5406'
    video: ''
  -
    code: code11
    reference: '4896'
    video: ''
  -
    code: code12
    reference: '4466'
    video: ''
  -
    code: code13
    reference: '5406'
    video: ''
  -
    code: code14
    reference: '5406'
    video: ''
